### ISSUE TITLE
handle long-expired certificates when using node cluster

### ISSUE THREAD

**Issue by coolaj86** [Daplie/letsencrypt-express#1]
In normal cases the webserver spends most of its time running and serving web pages. Occasionally it may restart, but due to the certificate renewal staggering it is very unlikely that two cores would just happen to try to renew the same certificate at the same time.

Here's a **highly unlikely** and **very unusual** scenario:

* I have a **node cluster** enabled server with 5 domains
* I shut it off for 3 months
* I turn it back on
* All of the certificates are now hard expired
* All of them renew at boot - 4 to 8 times each (once for each node in the cluster)
* I get rate-limited and blocked

But somewhere it will happen to someone, so this issue should get slated to be fixed within the next 3 months.

Maybe check for a lockfile and the mtime on that file must be within the last 30 seconds?

Or instruct the user to have a function run before forking?

Or have a little `process.on('data')` and `worker.send()` IPC?

**Comment by m-wellnitz** [comment]
maybe in this case it's simpler to add a random time (10-40 sec.), recheck, and if its already an issue to renew the certificate.

**Comment by coolaj86** [comment]
I'm closing this because it's really just too much brain power on a problem that is too unusual. We can reopen this if it becomes an actual problem in the real world.

**Comment by coolaj86** [comment]
Here's the solution for v2: https://github.com/Daplie/letsencrypt-cluster
