### ISSUE TITLE
Letsencrypt and vhost?

### ISSUE THREAD

**Issue by fbonesso** [Daplie/letsencrypt-express#10]
Hello guys!

I would like to know if is possible to run letsencrypt with multiples vhosts in the same application.

Thanks!

**Comment by coolaj86** [comment]
Yes, it totally is. Making that programmatically possible is part of why I built it out in node.

**Comment by fbonesso** [comment]
I'm trying to make this work, but I don't know if I'm doing it right.

`chokidar.watch('./domains', { depth: 1, awaitWriteFinish: true } ).on('all', function(event, path) {
    if (path.split('/').length > 2) {
        var domain = path.split('/')[1];
         
        if (path.split('/')[2] == "app.js") {
            if (event == 'add') {
            	try {
                    app.use(vhost(domain, require('./domains/' + domain + '/app')));
                     
                    console.log(domain);
                }
                catch (error) {
                    var date = new Date();
 
                    fs.appendFile('logs/domains.txt', date + ' - ' + domain + ' - ' + error + '\n');

                    console.log(error);
                }
            }
        }
    }
});

lex.create({
        configDir: './letsencrypt.config',
        onRequest: app,
        letsencrypt: null,
        approveRegistration: function (hostname, cb) {
            cb(null, {
              	domains: [hostname],
                email: 'letsencrypt@' + hostname,
               	agreeTos: true
        	});
	}
}).listen([3000], [443], function () { });`

**Comment by fbonesso** [comment]
I'm trying to make this work, but I don't know if I'm doing it right.

```
chokidar.watch('./domains', { depth: 1, awaitWriteFinish: true } ).on('all', function(event, path) {
    if (path.split('/').length > 2) {
        var domain = path.split('/')[1];
         
        if (path.split('/')[2] == "app.js") {
            if (event == 'add') {
            	try {
                    app.use(vhost(domain, require('./domains/' + domain + '/app')));
                     
                    console.log(domain);
                }
                catch (error) {
                    var date = new Date();
 
                    fs.appendFile('logs/domains.txt', date + ' - ' + domain + ' - ' + error + '\n');

                    console.log(error);
                }
            }
        }
    }
});

lex.create({
        configDir: './letsencrypt.config',
        onRequest: app,
        letsencrypt: null,
        approveRegistration: function (hostname, cb) {
            cb(null, {
              	domains: [hostname],
                email: 'letsencrypt@' + hostname,
               	agreeTos: true
        	});
	}
}).listen([3000], [443], function () { });
```

**Comment by coolaj86** [comment]
There's nothing that you need to configure or change with `letsencrypt-express`, so I'm going to close this issue.

However, I would suggest that you take a look at https://github.com/Daplie/letsencrypt-express/blob/master/bin/lex.js and use a similar API-oriented process rather than trying to watch the directory for changes.

Also, since you're doing this very dynamically `vhost` probably won't work as well for what you need. I would suggest dynamically building an object like this:

```javascript
{ 'mydomain.com': true
, 'myotherdomain.com': true
}
```

And each time you encounter a domain that is not in the object, then you look on the file system for it.
