### ISSUE TITLE
crash after certification 

### ISSUE THREAD

**Issue by accSone** [Daplie/letsencrypt-express#11]
Have a crash each time after the certs are written back to config path. Certification process itself runs well and return valid certs. Even the certs are written to config path and can be used afterwards without problem. Same happens in test mode. Running on Ubuntu Server 14.04 LTS. Node v5.4.1, phython2.7
Thanks for any help! 

web@node1:~/letshttps$ node server.js
ENCRYPT __ALL__ THE DOMAINS!
ENCRYPT __ALL__ THE DOMAINS!
ENCRYPT __ALL__ THE DOMAINS!
approveRegistration
Unhandled rejection TypeError: Cannot read property 'indexOf' of undefined
    at /home/web/letshttps/node_modules/pyconf/index.js:131:32
    at Array.forEach (native)
    at stringifyPythonConf (/home/web/letshttps/node_modules/pyconf/index.js:109:20)
    at Object.writePythonConfFile [as writeFile] (/home/web/letshttps/node_modules/pyconf/index.js:157:3)
    at Object.tryCatcher (/home/web/letshttps/node_modules/bluebird/js/release/util.js:11:23)
    at Object.ret [as writeFileAsync] (eval at <anonymous> (/home/web/letshttps/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /home/web/letshttps/node_modules/letsencrypt/lib/core.js:112:19
    at tryCatcher (/home/web/letshttps/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/web/letshttps/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/home/web/letshttps/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/home/web/letshttps/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/home/web/letshttps/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/home/web/letshttps/node_modules/bluebird/js/release/promise.js:615:18)
    at /home/web/letshttps/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/web/letshttps/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by hugojosefson** [comment]
I get `Cannot read property 'indexOf' of undefined` in `pyconf` too, just like above.

**Comment by coolaj86** [comment]
I wanted to let you know that I saw your issue come it, but I haven't had a chance to look at it yet, I will come back to this, hopefully later this week.

**Comment by hugojosefson** [comment]
Great! Thanks for the status update, @coolaj86. Do let me know if there is anything I can do or check to assist.

**Comment by coolaj86** [comment]
Off the cuff it sounds like a permission error, but in a few days perhaps we can get on skype and walk through it. My error handling is as good as it could be right now.

**Comment by hugojosefson** [comment]
Sounds good. Let me know, and I'll make time.

**Comment by RobertWarrenGilmore** [comment]
I think that the second argument in [this call](https://github.com/Daplie/node-letsencrypt/blob/master/lib/core.js#L112) is in the wrong format or something, because the serialisation of that object looks like what's failing. If you follow the stack trace, you get to [a place where the code tries to check if a string starts with "#"](https://github.com/coolaj86/node-config-python/blob/master/index.js#L131), but in practice that string is undefined.

**Comment by accSone** [comment]
Yes, routine crashing because pyobj contains a undefined entry in its array as a last array item. This happens in the 2nd call of writeRenewalConfig(args)  in line 111 from  letsencrypt\lib\core.js 

 return mkdirpAsync(path.dirname(args.renewalPath)).then(function () {
    return pyconf.writeFileAsync(args.renewalPath, pyobj);
  }).then(function () {
    return pyobj;
  });

Not yet sure where this undefined entry is added to the array. Any thoughts?

**Comment by coolaj86** [comment]
I'm finally looking into this. Sorry for the long wait.

**Comment by hugojosefson** [comment]
Great! Thanks @coolaj86 for investigating. Do let me know if there is any way I can assist.

**Comment by coolaj86** [comment]
I think it's actually due to a race condition where the browser makes multiple requests triggering approveRegistration in SNICallback 6 times.

I think the solution will be to make the original domain registration manual (via a simple POST) and remove the approveRegistration callback entirely.

Testing...

**Comment by coolaj86** [comment]
I found that the `registerHelper` callback is firing well before it actually completes. I'm probably accidentally not returning a promise somewhere down in the bowels of the code.

Once I get that figured out then I'll investigate the issue with the pyconf having a mismatched number of lines and throwing the `indexOf` error.

**Comment by hugojosefson** [comment]
Thanks for the update! It's really interesting to see the progress :)

**Comment by accSone** [comment]
Debugging Promise races is not easy. I heard that [Bluebird](https://github.com/petkaantonov/bluebird) can provide longStackTraces that might help.

**Comment by coolaj86** [comment]
v1.0.7 should close this issue.

updated `pyconf` to v1.1.2 and `letsencrypt` to v1.4.1

**Comment by hugojosefson** [comment]
Thanks a lot @coolaj86! I hope to try it out soon :+1:

**Comment by accSone** [comment]
Hi, v1.4.1 is not avail thru npm. Could you please update?

**Comment by accSone** [comment]
Confirmed. It works without crash. Thanks!
