### ISSUE TITLE
security certificate is from localhost.daplie.com

### ISSUE THREAD

**Issue by FaridSafi** [Daplie/letsencrypt-express#12]
Hello @coolaj86,
Thank you for this package. It works well for my main domain https://nomads.ly

I created a certificate for the domains nomads.ly and api.nomads.ly but I have an issue with the second one "security certificate is from localhost.daplie.com"

![screen shot 2016-01-17 at 22 37 02](https://cloud.githubusercontent.com/assets/388375/12380126/fd925d9e-bd6a-11e5-8e83-1bd0ae781e6c.png)

Is there an option to handle multiple domains ?

The code I use is simple
```js
lex.create('/etc/letsencrypt', app).listen([3000], [443, 5001], function () {}); /* 80 is redirected to 3000 */
```

**Comment by coolaj86** [comment]
I will look into this soon (within a week). It should "just work", but obviously we have a problem.

**Comment by AtlasDev** [comment]
I can confirm this issue:

http://puu.sh/mEnnQ/d204fb2679.png

**Comment by justinmc** [comment]
Same problem here.

**Comment by RobertWarrenGilmore** [comment]
:+1:

**Comment by RobertWarrenGilmore** [comment]
I've been poking around in /lib/standalone.js and I haven't found any code that sets the key and the certificate of the server when a renewal or registration occurs. Isn't that what this library is meant to do?

**Comment by RobertWarrenGilmore** [comment]
https://github.com/Daplie/letsencrypt-express/blob/master/lib/standalone.js#L164

It seems like this `listen` function starts some servers, but doesn't bother to restart them using the new cert when the cert changes.

**Comment by RobertWarrenGilmore** [comment]
My work-around is to listen to changes to privkey.pem in the file system. When such a change fires, I close the servers created by letsencrypt-express, read the new keys from the file system, and call letsencrypt-express.listen() again. Renewal time will reveal whether this works.

**Comment by coolaj86** [comment]
Sorry guys, I've just been bogged down. This is still high-priority on my TODOs.

Explanation
=========

A node server must have default certificates, so I provide some semi-bogus certificates (they work for localhost.daplie.com, which points to localhost and you can use /etc/hosts to point anywhere you want) for the purpose of the required defaults.

**Comment by hansjd** [comment]
my work around, is to use [letencrypt-cli](https://github.com/Daplie/letsencrypt-cli)
```
letsencrypt certonly \
  --agree-tos --email john.doe@example.com \
  --standalone \
  --domains www.example.com \
  --server https://acme-staging.api.letsencrypt.org/directory \
  --config-dir ~/letsencrypt/etc
```
does not work for me to use multple domains, so one at the time.

copy live directory from --config-dir ~/letsencrypt/etc (or where you set your config-dir), to your config dir defined in your express server, (mine looks like this configDir: './letsencrypt/letsencrypt.config')
```
cp ~/letsencrypt/etc/live/ {project-directory}/letsencrypt/letsencrypt.config/
```

**Comment by coolaj86** [comment]
Try v1.0.8 and all should be well.
