### ISSUE TITLE
[STICKY] [LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED

### ISSUE THREAD

**Issue by colinangusmackay** [Daplie/letsencrypt-express#18]
I noticed this in the console:

    [LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)

As per request, I'm raising an issue to remind you of this. I've only seen this once. I'm not sure what caused it, and I can't seem to replicate it.

**Comment by coolaj86** [comment]
I need to implement this for HPKP support (so that you could specify a private key instead of generating a new one).

So far no one has needed this, so I'm pushing it off for now. But I will need it myself in the future and so I will implement it as soon as someone complains, especially if that someone is me.

**Comment by jasonmayes** [comment]
Was following this tutorial (manual version): https://github.com/Daplie/letsencrypt-express and have run into this issue too when trying to execute:

letsencrypt certonly --standalone --config-dir ~/letsencrypt/etc --aos --domains <ipofserver> --email blah@blah.com

**Comment by nrw** [comment]
i just ran into this, too

**Comment by coolaj86** [comment]
https://github.com/Daplie/letsencrypt-express/issues/21

**Comment by coolaj86** [comment]
I should just take that warning out... it was supposed to only show up when you were actually using domainKeyPath, but since there's a default value it always shows up always.

It's benign. Unless you know you're trying to use a domainKey (and so far no one has), don't worry about it.

**Comment by coolaj86** [comment]
I'm closing this as it's about to be fixed along with https://github.com/Daplie/node-letsencrypt/issues/27 as soon as I push changes.
