### ISSUE TITLE
`dest.end is not a function` in production mode

### ISSUE THREAD

**Issue by justinmc** [Daplie/letsencrypt-express#25]
I'm seeing the above error when visiting the site with LEX running in production mode (meaning it's required without the `.testing()`).

I actually got this working in testing mode on my production server.  The server started up, and on visiting it at https it generated the certificates and logged success to the server.  The browser still wouldn't load the site though, because it didn't trust the certificate (which was given as `happy hacker fake CA`).  I'm assuming this is just because of testing mode.

So then trying to run it in production mode, it starts up fine, but visiting it in the browser causes it to crash:

```
Account '...' was corrupt. No big deal (I think?). Creating a new one...
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
  express:router dispatching GET / +7s
  express:router query  : / +1ms
  express:router expressInit  : / +1ms
  express:router compression  : / +0ms
  express:router cookieParser  : / +1ms
  express:router <anonymous>  : / +2ms
  express:router favicon  : / +0ms
  express:router logger  : / +1ms
  express:router jsonParser  : / +2ms
  express:router urlencodedParser  : / +0ms
  express:router cookieParser  : / +0ms
  express:router serveStatic  : / +1ms
_stream_readable.js:490
    dest.end();
         ^

TypeError: dest.end is not a function
    at Stream.onend (_stream_readable.js:490:10)
    at Stream.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

FWIW, looking in my configDir after this, I do see that the keys were generated.

**Comment by jamesmehorter** [comment]
I'm getting this as well, though testing() mode produces the same error

**Comment by RobertWarrenGilmore** [comment]
:+1:

**Comment by mahmalsami** [comment]
:+1:  was facing the same issue, downgrading fixed the problem.
Subscribing to be updated once it's fixed on the future releases.

**Comment by justinmc** [comment]
That worked for me too.  @coolaj86 if you need more details for fixing this on future releases let me know, I can still reproduce it if I upgrade.  If you can point me in the right direction I might be able to help out too.

**Comment by nwestbury** [comment]
@mahmalsami I'm having the same issue. What version do I need to downgrade to?

**Comment by DurinMusicspear** [comment]
Also got this issue. When searching for a solution i found this issue in Express that seems to be related: https://github.com/expressjs/express/issues/2761

**Comment by danzel** [comment]
letsencrypt-express 1.1.2 Moved from ```https``` module to ```http2``` module which is not compatible with express as posted above ^^ :(

**Comment by coolaj86** [comment]
I removed the dependency on http2 and updated the documentation accordingly, just forgot to come back here and update.

Also, I'm using express and http2 and haven't had any problems.

Note that I'm using the stable version of express (4.x) and not the alpha 5.x. I see the issue on the express github references to the alpha version.

I'm closing this for now, please feel free to use `spdy` or another module if `http2` doesn't work for you. Sorry for leaving this hanging so long. Small startup. Lots of work. :(

**Comment by danzel** [comment]
I don't see the commits for this. Did you forget to push?
Otherwise, thanks :)

**Comment by coolaj86** [comment]
My bad, it was the other section I changed:

https://github.com/Daplie/letsencrypt-express#use-with-raw-http--https-modules

Thanks. I'll have to go double check on https / http2 / spdy and update the express section.

**Comment by coolaj86** [comment]
I just swapped out http2 for spdy and pushed. Give that a try.

Also, I found https://github.com/molnarg/node-http2/issues/100. I thought I had been using it with express, but it turns out I was using https in my actual app.
