### ISSUE TITLE
I really wish this worked ...

### ISSUE THREAD

**Issue by muchavie** [Daplie/letsencrypt-express#29]
sudo /home/pogilvie/Local/node/bin/letsencrypt certonly --standalone   --config-dir ~/letsencrypt/etc   --agree-tos --domains www.ogilvie.us.com --email code@ogilvie.us.com

Account 'a9fb0e573f9af04e47d33fa766a35094' was corrupt. No big deal (I think?). Creating a new one...
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
[DEBUG le/lib/core.js] registeryAsync err
Error: The CA was unable to validate the file you provisioned.

**Comment by coolaj86** [comment]
```
Error: The CA was unable to validate the file you provisioned
```

I'd recommend just blowing away the letsencrypt directory `rm -rf letsencrypt/etc` and then making sure that `ping www.ogilvie.us.com` shows the same ip address as `ifconfig` on the server.

**Comment by coolaj86** [comment]
closing this issue

**Comment by muchavie** [comment]
I'm cool with that.   I got certificates working by running the standalone tool by hand and pointing raw node https at the certs.   

My problem was that I was using an iptables firewall command to mascarade port 443 to an unprivileged port so I wouldn't need to run my server as root.   I suspect your software is fine.  

BTW I'm a javascript jabber fan.  :)   Will get back to trying this module again as time allows!
