### ISSUE TITLE
localhost dev

### ISSUE THREAD

**Issue by philholden** [Daplie/letsencrypt-express#30]
I am new to developing with https and would appreciate some instructions about development under https i.e. before I deploy while testing on my own machine under localhost how do I get a certificate?

I need to use https in dev because I want to use browser features like `getUserMedia` and `fullScreen` which now require https.

**Comment by coolaj86** [comment]
You can't use letsencrypt for that scenario, but you can use https://github.com/Daplie/localhost.daplie.com-certificates
