### ISSUE TITLE
Accessing challenge on specific port?

### ISSUE THREAD

**Issue by Zebusch** [Daplie/letsencrypt-express#32]
Perhaps i am missing something but i setup the site to listen to 3000/3001 like this:
```
var lex = LEX.create({
  configDir: require('os').homedir() + '/letsencrypt/etc'
, approveRegistration: function (hostname, cb) { // leave `null` to disable automatic registration
    // Note: this is the place to check your database to get the user associated with this domain
    cb(null, {
      domains: ['xxx.yyy.zzz']
    , email: 'x.y@z.com' // user@example.com
    , agreeTos: true
    });
  }
});

lex.listen([3000], [3001, 5001], function () {
  var protocol = ('requestCert' in this) ? 'https': 'http';
  console.log("Listening at " + protocol + '://localhost:' + this.address().port);
});

```
However, the challenge is trying to be reached on port 80. So instead of "http://xxx.yyy.zzz:3000/.well-known/...." it is trying to get challenge from "http://xxx.yyy.zzz/.well-known/....". (which obviously does not work since that port is not listened to)

Is this by design?

**Comment by coolaj86** [comment]
Unfortunately you do not get to choose which port the challenge comes in on: https://github.com/letsencrypt/acme-spec/issues/33
