### ISSUE TITLE
Koa Example

### ISSUE THREAD

**Issue by ennisj9** [Daplie/letsencrypt-express#33]
Not really knowing what I was doing I ran into quite a bit of issues trying to use the Koa example, which I blindly followed to a T . First, that listening only on port 443 fails the acme handhsake. Second, that Koa and http2 don't play nice.  Knowing what I know now the need for port 80 makes sense, but was confusing.  

I think something like this would be more helpful for the uninitiated:

```javascript
var koa = require('koa');
var forceSSL = require('koa-force-ssl');
var spdy = require('spdy');
var LEX = require('letsencrypt-express');
var http = require('http');

var app = koa();
app.use(forceSSL());

var noSSL = http.createServer(LEX.createAcmeResponder(lex, app.callback()));
noSSL.listen(80);
var server = spdy.createServer(lex.httpsOptions, LEX.createAcmeResponder(lex, app.callback()));
server.listen(443);
```

**Comment by coolaj86** [comment]
This is awesome. Thanks!

I'll see about updating the README here in a moment...

**Comment by coolaj86** [comment]
Take a look at my updated example and let me know if that works for you.

**Comment by ennisj9** [comment]
Looks great thanks.
