### ISSUE TITLE
Usage in cluster mode?

### ISSUE THREAD

**Issue by Rush** [Daplie/letsencrypt-express#39]
Hello, I'm the author of http-master (https://github.com/virtkick/http-master) and would like to use your module to implement letsencrypt support. The architecture I have is one central process and multiple workers. Certificates from disk are managed by the master process and serialized to individual workers.

With letsencrypt-express I imagine that the master process would need to have the letsencrypt state and actually issue the renewal requests, whereas the workers would have to ask the master process for certificates data. Can your module accomodate such use case?

**Comment by Rush** [comment]
I managed to worked around the limitation: 

This is how I handle SNI:
https://github.com/virtkick/http-master/blob/master/modules/letsencrypt.js#L30

This is a slightly modified SNI callback:
https://github.com/virtkick/http-master/blob/master/lib/letsencryptSniCallback.js#L8
This is how I call a modified SNI callback:
https://github.com/virtkick/http-master/blob/master/modules/letsencrypt.js#L30

Would you be with a PR that allows for passing custom createSecureContext implementation? That's about the only thing my code required to work with your awesome library.

**Comment by coolaj86** [comment]
Yeah, I'd love that.

In fact, at some point in the future (if I ever have time), I'll be refactoring `letsencrypt` so that the requests go through a master process anyway (I'm also using cluster, but rely on the randomness of the timers I put in `letsencrypt` to be "good enough" for now).

Nice hat, btw.

**Comment by Rush** [comment]
> Yeah, I'd love that.
I'd appreciate your opinion on my PR. 

> Nice hat, btw.

Thanks. :-) It's beaver.

> I'll be refactoring letsencrypt so that the requests go through a master process

I'll hope this will be optional though cause cluster is not modular enough to be used by two independent libraries at the same time. My project/library http-master uses 0 workers by default and the worker abstraction is good enough to have the same code for cluster and non-cluster usage.

**Comment by coolaj86** [comment]
Boom! https://github.com/Daplie/letsencrypt-cluster

I just ran the examples and each of the individual plugins and modules have already been tested.

That was actually the base work for `letsencrypt-express`, now I just have to remove a few parts, add a few defaults, and republish it under that name.

**Comment by coolaj86** [comment]
I didn't test renewals there, but they've already been tested in `node-letsencrypt`, so I'm feeling good about it.

**Comment by coolaj86** [comment]
P.S. Would you like to take on any of these simple database adapters for storing accounts and certificates? https://github.com/Daplie/node-letsencrypt/issues/39
