### ISSUE TITLE
<Object> has no method 'homedir'

### ISSUE THREAD

**Issue by martinwells** [Daplie/letsencrypt-express#41]
/usr/lib/node_modules/letsencrypt-express/bin/lex.js:9
var homedir = require('os').homedir();
                            ^
TypeError: Object #<Object> has no method 'homedir'

**Comment by coolaj86** [comment]
You've got an ancient version of node that's a few years old (v0.10 or so, I'm guessing) and you should upgrade.

**Comment by coolaj86** [comment]
Also, you can shim / polyfill your version of node to fix it:

```javascript
var path = require('path');

require('os').homedir = function (subDir) {
  var baseDir = process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];
  return (subDir) ? path.join(baseDir, subDir) : baseDir;
};
```

**Comment by martinwells** [comment]
Yep. That was it. Doh!
