### ISSUE TITLE
the README has a warning about the approveRegistration callback, but doesn't say how to write a safe one

### ISSUE THREAD

**Issue by davidflanagan** [Daplie/letsencrypt-express#44]
The Setup section of the README cautions against using the approveRegistration callback that is shown, but does not say what needs to be done to make it safe.

I'm guessing that we just need to make sure that the hostname is the expected one, but it would be nice to have that more clear.

**Comment by coolaj86** [comment]
It's up to you how you want to check - if you want to use a database, or read from a file, or whatever, but you should do something to make sure you're not accepting requests for domains that you don't own.

That's all.

Help me make this more clear and I'll update the README and merge it in.

**Comment by davidflanagan** [comment]
Thanks. I created PR #47 with code that is clearer to me.  See what you think.
