### ISSUE TITLE
Multiple domains under one certificate

### ISSUE THREAD

**Issue by Abaggio2020** [Daplie/letsencrypt-express#48]
Hello,

I've been going through all the examples and documentation and I haven't been able to find anything that might make this seem possible.

I have an API using subdomains and I was hoping to request just one certificate for all the domains. I noticed in my testing I ended up hitting the rate limit cap to the number of certs I could get (Was using production cert server for testing). 

Is there a way to do this? Or is the best option going to be manually pulling the cert using the CLI tool?

Appreciate any feedback on this!

**Comment by wmertens** [comment]
How many domains do you have? I simply added my 3 domains to the domains array in the registration callback and got a single cert with dns alternates for each domain…

**Comment by coolaj86** [comment]
The problem here is that with the python-style config files there's no way to know which config file was used to issue a cert and therefore no way to know how to renew it.

I'm closing the discussion here, but let's continue it over at https://github.com/Daplie/node-letsencrypt/issues/32
