### ISSUE TITLE
Certificates expired

### ISSUE THREAD

**Issue by Rush** [Daplie/letsencrypt-express#53]
Only after commenting out this piece of code https://github.com/Daplie/letsencrypt-express/blob/master/lib/sni-callback.js#L66 the certs were renewed.

Any ideas?

**Comment by mannyvergel** [comment]
My certificates also expired. Any idea why it's not renewing automatically?

**Comment by jhermsmeier** [comment]
Same here – certificates expired, renewal wasn't triggered.
Commented out that line, which caused the following to show up in the logs:
```
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
```
But then, as stated in #18 – apparently that's nothing to worry about.
And the certs have still not been renewed.

Any pointers on what to look for, or how to debug this, @coolaj86?

**Comment by Rush** [comment]
Could you comment out the line I mentioned in the first post? I'm gonna investigate this issue this week.

**Comment by jhermsmeier** [comment]
> Commented out that line, which caused the following to show up in the logs:
> [...]
> Took a while, but renewed the certs now.

I did, and it works that way 👍

**Comment by cveilleux** [comment]
+1

certs were not being renewed and commenting out the line solved the issue.

**Comment by Rush** [comment]
I will look into developing a proper fix. Probably passing `failedWait` in options as `-1` would be a better workaround with no intervention inside the code.

**Comment by coolaj86** [comment]
I'm finally working on the rewriting the crypto methods, which will probably fix the renewal issue.

https://github.com/Daplie/rsa-compat.js/issues/2

That said, I do want to look into why the wait timeout would make any change to the renewal succeeding or failing.

**Comment by Rush** [comment]
I just had a case when a certificate expired even with failedWait removed. I had to restart the process for node-letsencrypt to issue a new one.

**Comment by coolaj86** [comment]
I'm working on this tonight and tomorrow. I'm going to take your advice @rush on using x509.js to view cert info.

**Comment by Rush** [comment]
@coolaj86 a tip for testing, you can install a `cert-scan` from `http-master` via `npm install -g http-master`. Then you can check all certs via `cert-scan /path/to/letsencrypt/directory`. It will show all validity dates.

**Comment by coolaj86** [comment]
Thanks!

**Comment by coolaj86** [comment]
Finally!!! Fully implemented and completely fixed. Just published as letsencrypt-express v2.0.0, based on node-letsencrypt v2.1.0

See the new README.md

**Comment by jhermsmeier** [comment]
Sweet! Is npm just being slow with cache invalidation now, or is it not yet published to npm?
```
$ npm info letsencrypt-express version
npm http request GET https://registry.npmjs.org/letsencrypt-express
npm http 200 https://registry.npmjs.org/letsencrypt-express
1.2.0
```

**Comment by coolaj86** [comment]
Try now.

I had a typo in the package.json so it actually published under the wrong name.
