### ISSUE TITLE
Custom Logger

### ISSUE THREAD

**Issue by calmdev** [Daplie/letsencrypt-express#54]
Hey! Are you open to the idea of allowing this to accept a custom logger instance?  Right now everything is dumped to the console, but I feel it'd be more flexible if a logger could be provided so logging can be sent to any transport layers being used by the custom logger. Console would be used by default, but if a logger is provided then that instead. 

For example, I'm using [Winston](https://github.com/winstonjs/winston) with several transport layers: console, file, email and paper trail app. When logging, the messages are sent to all those locations for me. 

What do you think?

**Comment by calmdev** [comment]
I took a different approach and overrode console methods to use winston.

**Comment by JaniszM** [comment]
Overriding console method is not good idea. I would like to know if I can log the output to the file.
