### ISSUE TITLE
When to use `duplicate: true` / auto-adjust certs with new domains?

### ISSUE THREAD

**Issue by wmertens** [Daplie/letsencrypt-express#57]
See https://github.com/keystonejs/keystone/issues/3149

## Problem

When you change the list of accepted domains, but the cert is still fresh, letsencrypt won't request a new certificate.

## Possible solutions

* Set `duplicate: true` on all requests
  * Problem: Every time you restart the server, it will request a new cert, even if the previous one is valid for the current domain

* Set `duplicate: true` only if the domain list changed
  * Problem: How to maintain that state, what if the renew didn't work

* Have letsencrypt automatically determine if a domain is missing from the cert and renew
  * This would seem to be the best solution from my perspective… Not sure if this is even possible?

**Comment by wmertens** [comment]
Is this the correct place to ask this, should I ask elsewhere?

**Comment by coolaj86** [comment]
I would say this is a question for node-letsencrypt.

However, once the renewal is fixed (which I finally started working on again yesterday and will continue tomorrow) I don't think this will be a problem anymore.

**Comment by coolaj86** [comment]
Renewal is fixed in letsencrypt-express v2.0.0, based on node-letsencrypt v2.1.0

See the new README.md
