### ISSUE TITLE
OpenSLL installation required on Windows

### ISSUE THREAD

**Issue by tommitytom** [Daplie/letsencrypt-express#62]
Hey guys!  Just thought I'd mention that as per the Ursa documentation (https://github.com/quartzjer/ursa#windows-install), an installation of OpenSSL is required on Windows.  Without it the build fails!  I didn't see this in your documentation anywhere and had to go on a bit of a hunt to find the solution so thought it might be worth letting you know :)

**Comment by coolaj86** [comment]
Actually, you don't have to build `ursa`. It's an optional dependency. Key generation will work quicker with `ursa` than with `forge`, but both are implemented.
