### ISSUE TITLE
Cant run example

### ISSUE THREAD

**Issue by benag** [Daplie/letsencrypt-express#7]
Using the minimal example i get the following error:
Cannot find module 'localhost.daplie.com-certificates'

**Comment by coolaj86** [comment]
Fixing momentarily...

**Comment by coolaj86** [comment]
try v1.0.4

**Comment by benag** [comment]
like that? npm install --save-dev letsencrypt-express@1.04
doesn't work..

**Comment by benag** [comment]
[LEX] creating sniCallback {
  "debug": true,
  "webrootPath": "/tmp/acme-challenge",
  "configDir": "/home/ben/letsencrypt/etc",
  "privkeyPath": "/home/ben/letsencrypt/etc/live/:hostname/privkey.pem",
  "fullchainPath": "/home/ben/letsencrypt/etc/live/:hostname/fullchain.pem",
  "certPath": "/home/ben/letsencrypt/etc/live/:hostname/cert.pem",
  "chainPath": "/home/ben/letsencrypt/etc/live/:hostname/chain.pem",
  "server": "https://acme-staging.api.letsencrypt.org/directory",
  "letsencrypt": {
    "backend": {}
  }
}
/home/ben/projects/getMoving/getMoving/node_modules/letsencrypt-express/lib/standalone.js:188
    plainPorts.forEach(function (addr) {
               ^
TypeError: undefined is not a function
    at Object.listen (/home/ben/projects/getMoving/getMoving/node_modules/letsencrypt-express/lib/standalone.js:188:16)
    at Object.<anonymous> (/home/ben/projects/getMoving/getMoving/app.js:60:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by benag** [comment]
my code:
lex.create(app).listen(3000, function() {
        console.log("Express server listening on port: " );
    });

**Comment by coolaj86** [comment]
`listen` takes two arrays (for plain and tls ports), not one number

```
.listen([80], [443, 5001], function () {
  console.log("ENCRYPT __ALL__ THE DOMAINS!");
});
```

I should probably make an error message for that...

**Comment by benag** [comment]
I have changed to:
lex.create(app).listen([3000], [443, 5001], function () {
        console.log("ENCRYPT __ALL__ THE DOMAINS!");
    });

However when i do:
https://localhost:3000/ or https://localhost
It doesn't work..
(I am new to SSL..can i test on local?)

**Comment by coolaj86** [comment]
https://localhost.daplie.com is the testing domain for localhost.

You can't test a real domain on localhost though, you'd have to run it on your server.

**Comment by coolaj86** [comment]
Did that work? Can I close this?

**Comment by coolaj86** [comment]
Since I haven't heard back, I'm closing this.
