### ISSUE TITLE
Unable to work

### ISSUE THREAD

**Issue by sirakoff** [Daplie/letsencrypt-express#75]
I keep getting 
`[le/core.js] domainKeyPath: undefined`
` AutoSNI LetsEncrypt Error: [TypeError: path must be a string]`
`Will fall back to self signed certificate.`

**Comment by coolaj86** [comment]
Those errors aren't coming from this module, but some other module that uses this one (or one of the lower level modules).

Take a look at the README for v2.0.0 (just published moments ago) and try with that.
