### ISSUE TITLE
Example crashes unless ``getCertificates`` is passed to ``leSni.create()`` options

### ISSUE THREAD

**Issue by Slayer95** [Daplie/letsencrypt-express#77]
What should that function look like anyway? :(

**Comment by coolaj86** [comment]
I did a demo with this last night and didn't have this error. Will you paste the exact example you're referring to?

**Comment by coolaj86** [comment]
Oh, I see what you're saying.

I now commented that out in the example. You're not likely to need to replace `le-sni-auto` unless you're doing some really low-level stuff or you want to use node cluster contrary to the way I show in letsencrypt-cluster.

**Comment by Slayer95** [comment]
Oh, I see. Thanks!
