### ISSUE TITLE
Some Errors with Example

### ISSUE THREAD

**Issue by Dimtime** [Daplie/letsencrypt-express#79]
Simple mistake in code here:
![1](https://cloud.githubusercontent.com/assets/16452588/17809623/9387f260-6620-11e6-8bd6-089e2cf81e0c.jpg)

When server run and try go to test site:
![2](https://cloud.githubusercontent.com/assets/16452588/17809622/93841dca-6620-11e6-8a89-37b80cf8c293.jpg)

Site fine in https, but when try loading from http:
"[500] Developer Error: app.use('/', le.middleware()) or le.middleware(app)"

Maybe i do something wrong... But code get from example...

**Comment by coolaj86** [comment]
Thank you sir!
