### ISSUE TITLE
This certificate was signed by an untrusted issuer

### ISSUE THREAD

**Issue by HsuTing** [Daplie/letsencrypt-express#83]
I do a testing like [this](https://github.com/Daplie/letsencrypt-express#usage), but I get a problem about `this certificate was signed by an untrusted issuer`. How can I fix this error?

**Comment by Dimtime** [comment]
Error in browser? You need check this and change string for production:
```
var lex = require('letsencrypt-express').create({
  // set to https://acme-v01.api.letsencrypt.org/directory in production
  server: 'staging'
```

**Comment by HsuTing** [comment]
Oh, my fault. I did not note that. Thank you for your answer.
