### ISSUE TITLE
bluebird is not included in package.json

### ISSUE THREAD

**Issue by garenyondem** [Daplie/letsencrypt-express#89]
Causes 'Error: Cannot find module 'bluebird'' while trying to create server.

**Comment by xingped** [comment]
I just had this problem as well and I'm not sure if it has to do with this module in particular or another module up/down the line, but I nuked my node_modules folder and just re-ran `npm install` and bluebird was there. I think a different package forgot to include it.

**Comment by coolaj86** [comment]
Fixed in v2.0.5

bluebird is now optional
