### ISSUE TITLE
Android is not trusting certificate

### ISSUE THREAD

**Issue by zhoul-HS** [Daplie/letsencrypt-express#90]
I'm getting trust issues when using different versions of Android (4.4 and 6.0, others might work).
Take a look at this thread: https://community.letsencrypt.org/t/android-doesnt-trust-the-certificate/16498/16

The last comment suggests settings the "ca" field in the credentials as the chain file:

```javascript
   var privateKey = fs.readFileSync('path/to/your/private-key.pem'), 'utf8');
    var certificate = fs.readFileSync('path/to/your/cert.pem', 'utf8');

    // this is so important. Many tutorials forget to include chain.pem
    var ca = fs.readFileSync('path/to/your/chain.pem', 'utf8');

    var credentials = { 
        key: privateKey, 
        cert: certificate,
        ca: ca
    };

    httpsServer = https.createServer(credentials, yourExpressInstance);
```
How can I do this manually? the lex object returns a `chainPath` but it returns the template path `:config/live/:hostname/chain.pem` which I'm not sure if I should process manually or what?

to continue development, I manually set `lex.httpsOptions.ca = require('fs').readFileSync(<absolute path to chain.pem>)` and it works...

**Comment by coolaj86** [comment]
The person that gave you that advice about `ca` doesn't understand how the node.js https stack works (I made the same mistake before I found out the solution).

I believe this is in the documentation on the project page, but it's obviously not clear enough. I'd love your help fixing that.

You must concatenate `{ cert: certs.pem + certs.chain }`.

The reason the certificate is not trusted "on android" isn't due to android, but rather that on that particular device the intermediate certificate is not in the cache.

Alternatively, if it's an old Android device that hasn't received security updates in a while, it may not have current root certificates.

**Comment by coolaj86** [comment]
The fact that it worked is actually coincidence as a `chain` is not a `ca` in the same way that a cert is not a chain. What did happen is that as you were browsing and testing this you happened to visit another site that did have the proper intermediate (any site that had letsencrypt-issued certs) and it was cached, so when you went back to test and the browser cache for your site cleared it happened to already have the complete chain.

I know that sounds to convoluted to be true, but I dealt with the same problem and created a false solution: 
https://github.com/coolaj86/node-ssl-root-cas

**Comment by zhoul-HS** [comment]
I doubt it is a coincidence because if I remove that line, it stops working.
I still don't understand what's the solution?

**Comment by coolaj86** [comment]
Hmm... that's curious... because a Root CA is not an Intermediate Certificate and the `ca` option doesn't get sent to the browser, only the `cert` option does. The `openssl` command above can confirm either way.

The solution is to concatenate `certs.cert + certs.chain` and assign that to `cert`.

**Comment by coolaj86** [comment]
Actually, you're commenting here on `letsencrypt-express`, which doesn't make sense because the concatenation is already handled for you and `lex.httpsOptions` is only used when `servername` is failed to be sent by the client, which is a problem with MSIE <= 6 and Android <= 2.3

**Comment by coolaj86** [comment]
Show me a code snippet of how you're using this module.

**Comment by zhoul-HS** [comment]
```javascript
var lex = require('letsencrypt-express').create({
  server: 'https://acme-v01.api.letsencrypt.org/directory'
  , agreeTos: true
  , approveDomains: ['example.com']
  , email: 'dude@example.com'
  , challenges: { 'http-01': require('le-challenge-fs').create({ webrootPath: 
  '/tmp/acme-challenges' }) }
  , store: require('le-store-certbot').create({ webrootPath: '/tmp/acme-challenges' })

});

// handles acme-challenge and redirects to https
require('http').createServer(lex.middleware(require('redirect-https')())).listen(8080, 
function () {
  console.log("Listening for ACME http-01 challenges on", this.address());
});

// handles your app
var httpServer = require('https').createServer(lex.httpsOptions, lex.middleware(app))
.listen(port, function () {
  console.log("Listening for ACME tls-sni-01 challenges and serve app on", this.address());
});

```

i use an iptables rule to route 80 to 8080 (because you need admin to run node on port 80)

**Comment by coolaj86** [comment]
Have you run that openssl debug command I sent?

That will show you the actual certificate and chain that every browser will get.

You may have success manually including the ISRG Root CA and cross-root CAs in the OkHttp options as allowed CAs:
https://letsencrypt.org/certificates/

I'm going to close this issue as it appears to be specific to your use case, but I'll still help what I can.

**Comment by zhoul-HS** [comment]
what openssl command? don't see any here.

**Comment by zhoul-HS** [comment]
my last question wasn't answered :(

**Comment by coolaj86** [comment]
How odd... I don't know where I put it. I must have crossed the streams...

I think this is it though:

```bash
openssl s_client -showcerts \
  -connect example.com:443 \
  -servername example.com
```
