### ISSUE TITLE
Works with staging, but 100% CPU usage with live

### ISSUE THREAD

**Issue by danzel** [Daplie/letsencrypt-express#92]
Everything works correctly when I use the staging server, but when trying to use the live system nodejs just sits at 100% CPU usage and doesn't seem to get anywhere.
I've left it for a minute but still nothing :(

Relevant configuration code (this.app is an express app):
```
var lex = LEX.create({
	server: 'staging', //'https://acme-v01.api.letsencrypt.org/directory',
	email: 'my@email.address',
	agreeTos: true,
	approveDomains: ['my.domain']
});
http.createServer(lex.middleware(function redirectHttps(req, res) {
	res.setHeader('Location', 'https://' + req.headers.host + req.url);
	res.statusCode = 302;
	res.end('<!-- Hello Developer Person! Please use HTTPS instead -->');
})).listen(80, function () {
	console.log("Listening for ACME http-01 challenges on", this.address());
});
this.httpServer = https.createServer(lex.httpsOptions, lex.middleware(this.app));
this.httpServer.listen(443, function () {
	console.log("Listening for ACME tls-sni-01 challenges and serve app on", this.address());
});
```

logs:
```
Listening for ACME http-01 challenges on { address: '::', family: 'IPv6', port: 80 }
Listening for ACME tls-sni-01 challenges and serve app on { address: '::', family: 'IPv6', port: 443 }
```

Node v6.7.0 on ubuntu 14.04

I'm not really sure what to try next, anything will help, thanks!

**Comment by coolaj86** [comment]
Well, I can tell you that the only difference I can think of between staging and production is the url that is used.

Is your code any different between staging and production?

**Comment by danzel** [comment]
Not that I can think of.
I ran it with the production url (as commented out above), then edited the code to have `staging`, restarted the app and it managed to get keys (staging ones though).

One thing I thought of after posting this is that the domain name it is authenticating for goes through cloudflare.
The http to https redirect is handled by the app through (cloudflare passes through http traffic, but it handles the public https cert for the domain itself).

I have another app/domain I can play with, I'll see if I can reproduce it there when going through cloudflare.

**Comment by danzel** [comment]
Works perfectly with my app (and the QuickStart app) on my other host when going through cloudflare.... Must be something silly I'm doing.

**Comment by coolaj86** [comment]
"To err is human. To really screw things up requires a computer."

So who knows. Maybe it's you, or maybe it's black magic somewhere in the codes that you just happened to trigger somehow (like an infinite redirect through cloudflare).

I'll close this for now, but feel free to re-open if you think the problem lives here after more investigation.

**Comment by danzel** [comment]
Haha yeah thanks for this project :)
