### ISSUE TITLE
Where did Lex.createAcmeResponder go in 2.x?

### ISSUE THREAD

**Issue by mortie** [Daplie/letsencrypt-express#96]
Hi,

In letsencrypt-express 1.x, I used the function Lex.createAcmeResponder. What's the equivalent in letsencrypt-express 2.x?

**Comment by coolaj86** [comment]
`lex.createAcmeResponder()` is now `lex.middleware(require('redirect-https')())` or `lex.middleware(app)`

**Comment by mortie** [comment]
Awesome, thanks for your help.
