### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by jrattray13** [Daplie/letsencrypt-express#98]
![](https://i.snag.gy/ptk6Pu.jpg)

When I visit node server it says unsecured https certificate. I tried this last week on a different server and it all worked fine (except I am referring to ip rather than domain here: )

![](https://i.snag.gy/ukj5Ro.jpg)

Why does this time it not work? How do I define a loopback function (is this why it is not working?) Many thanks appreciate any insight.

**Comment by insightfuls** [comment]
The type of certificates issued by Let's Encrypt are "domain control validated" certificates. This means Let's Encrypt will vouch for the fact that your server is controlled by the same entity that controls the domain name registration (which is verified via DNS). Let's Encrypt will not, and as far as I know, there is not even an appropriate kind of certificate that will, vouch for the authenticity of an IP address. So what you are trying to do here is simply impossible. You can only obtain certificates for actual domain names.

**Comment by jrattray13** [comment]
thanks for the explanation, time to buy a domain for this ip!

**Comment by JonSilver** [comment]
FYI LetsEncrypt certs for dynamic DNS names work fine too, so you don't necessarily need to go registering a domain name for each IP address.
